num1=  input("1st no. :")
num2=  input("2nd no. :")
oprator= input("Oprator (+,-,*,/) :")
num1=int(num1)
num2=int(num2)
if oprator=="+" : print("Solution : " ,num1 +  num2) 
if oprator=="-" : print("Solution : " ,num1 - num2) 
if oprator=="/" : print("Solution : " ,num1 /  num2) 
if oprator=="*" : print("Solution : " , num1 *  num2) 
sys.exit()